### ISSUE TITLE
no touchable when using CustomLayoutOption

### ISSUE THREAD

**Issue by mamonraab** [TheAnkurPanchani/card_swiper#1]
hello itry to make my CustomLayoutOption  on top of wiper but  swiping the slide with touch fingers not working 

my code is 

` Swiper(itemCount: _sliddata.length,
 
         itemBuilder:  (context, index) {
           return imgbuildr(index);
         },

         scrollDirection: Axis.horizontal,

         loop: true,

         control: new SwiperControl(
             color: Colors.red
         ),

         pagination: new SwiperPagination(
             margin: new EdgeInsets.all(5.0),
             builder: new DotSwiperPaginationBuilder(
                 color: Colors.grey, activeColor: Colors.red)

         ),

         viewportFraction: 0.1,

         scale: 2,
         itemHeight: MediaQuery.of(context).size.height * 0.3,
         itemWidth: MediaQuery.of(context).size.width * 0.85 ,
         autoplayDelay: 9250,
         duration: 622,

         layout:
         SwiperLayout.CUSTOM,
         customLayoutOption: new CustomLayoutOption(
           startIndex: -1,
           stateCount: 3,

         ).addOpacity([
           0.6,
           0.6,
           1.0

         ])

             .addRotate([

           0.03,
           0.03,
           0.0

         ])

             .addScale([
           0.8,
           0.8,
           0.96

         ],Alignment.center )

             .addTranslate([
           //offset(left,upp)
           new Offset(-100.0, 5.0),
           new Offset(100 , 5.0 ),
           new Offset(0.0, 0.0)
         ]),
       ) ,`

**Comment by TheAnkurPanchani** [comment]
@mamonraab : Hi, Could you please provide a `main.dart` file with reproducible minimal code sample?

**Comment by mamonraab** [comment]
after double check the problem , it happened when i use the slider inside  a screen that is inside the TabBarView()  , when i remove it from there it work but i want to  keep using the TabBarView coz it is a big part on my app 
it is a large news app i will try to memic the problem and send a simple code

**Comment by mamonraab** [comment]
here is a link for the  problem , as mentioned when putting the swiper with my costum layout 
is not working [https://github.com/mamonraab/card_swiper_problem_demo](url)

**Comment by mamonraab** [comment]
also to mention this happen when using customLayoutOption  while using default settings work nice

**Comment by mamonraab** [comment]
any update ??

**Comment by TheAnkurPanchani** [comment]
I found cause of the problem in already opened issue under flutter repo. Here is the link,
https://github.com/flutter/flutter/issues/59555 

If you want swiper takes all the swipe gestures and doesn't want swipes to change tab views then you can use suggestion mentioned in the comment, Here is the link,
https://github.com/flutter/flutter/issues/59555#issuecomment-644819857

Try setting `physics: NeverScrollableScrollPhysics(),` in TabBarView

```dart
child: TabBarView(
  physics: const NeverScrollableScrollPhysics(),
  children: [
```
