### ISSUE TITLE
swiper pagination position

### ISSUE THREAD

**Issue by Jason-zzzz** [TheAnkurPanchani/card_swiper#12]
the **pagination.alignment** unused

![](https://user-images.githubusercontent.com/16592298/132328334-737c50e0-752b-4673-ac4c-be121d162d64.png)
![image](https://user-images.githubusercontent.com/16592298/132329161-18f3c778-e04e-4038-816e-2bd457e515ad.png)

**Comment by Jason-zzzz** [comment]
![image](https://user-images.githubusercontent.com/16592298/132328334-737c50e0-752b-4673-ac4c-be121d162d64.png)

**Comment by HuberyYang** [comment]
Encountered the same problem

**Comment by qiongshusheng** [comment]
Encountered the same problem

**Comment by HuberyYang** [comment]
谢谢！
