### ISSUE TITLE
How to keep alive when there are multiple pages?

### ISSUE THREAD

**Issue by BadReese** [TheAnkurPanchani/card_swiper#2]
as title said.

**Comment by TheAnkurPanchani** [comment]
You should try AutomaticKeepAliveClientMixin. A reference to know how it works: https://medium.com/manabie/flutter-simple-cheatsheet-4370a68f98b3

**Comment by RasitAyaz** [comment]
> You should try AutomaticKeepAliveClientMixin. A reference to know how it works: https://medium.com/manabie/flutter-simple-cheatsheet-4370a68f98b3

Just tried this but it does not seem to work. Pages are being reinitialized every time.

**Comment by whichname** [comment]
But if loop is true,  AutomaticKeepAliveClientMixin will be  not work.  So how can i do ?

**Comment by TheAnkurPanchani** [comment]
@whichname :  Please open another issue with some sample code to replicate.
