### ISSUE TITLE
how to stack from right instead of left?

### ISSUE THREAD

**Issue by zeeshanahmad0201** [TheAnkurPanchani/card_swiper#3]
I'm trying to design the following layout but I see there is no option to stack from the right. Just like in the image below
![Screenshot from 2021-07-16 17-07-56](https://user-images.githubusercontent.com/50322893/125945050-39b1f155-d6eb-47a5-aa35-fc8173127f45.png)

**Comment by TheAnkurPanchani** [comment]
Stack layout alignment is not supported at the moment. I will try to make the change in my free time. Meanwhile any contribution is welcomed. :pray:

**Comment by TheAnkurPanchani** [comment]
Latest version now supports parameter `axisDirection: AxisDirection.right`.
