### ISSUE TITLE
[bug] i can't use CustomLayoutOption

### ISSUE THREAD

**Issue by FIREIDEAS** [TheAnkurPanchani/card_swiper#31]
![image](https://user-images.githubusercontent.com/96883885/154510382-ae18fe8b-be58-4d8b-af71-764aecdaa241.png)

**Comment by sawsankgraham** [comment]
Same Here. Did you solve the issue?

**Comment by FIREIDEAS** [comment]
just downgrade to [1.0.4] and it will work.

**Comment by TheAnkurPanchani** [comment]
Please check updated README.
