### ISSUE TITLE
SwiperLayout.CUSTOM layout is not working as expected

### ISSUE THREAD

**Issue by Charlinjoeaht** [TheAnkurPanchani/card_swiper#34]
There are two problems while using SwiperLayout.CUSTOM (I am using **card_swiper: ^2.0.1**)

1. While using Next and Previous buttons the indexes are correctly moving but the swipe animation is going in reverse way
2. While using the swipe, the index is changing in reverse which is wrong too

https://user-images.githubusercontent.com/50817246/156263373-b6393f05-2453-4f3b-a2af-96613a1afcab.mov

**Comment by Charlinjoeaht** [comment]
As a workaround I am continuing with card_swiper: ^1.0.4

**Comment by TheAnkurPanchani** [comment]
v3 is released with this fix.
