### ISSUE TITLE
upgrade to flutter 3.0 

### ISSUE THREAD

**Issue by guchengxi1994** [TheAnkurPanchani/card_swiper#44]
WidgetsBinding.instance!.addPostFrameCallback 'WidgetsBinding' which excludes null

**Comment by jmguillens** [comment]
Agreed the solution is to remove the !

**Comment by tasaddaq-hussain** [comment]
where? remove !

**Comment by TheAnkurPanchani** [comment]
Latest release is with this fix. Please check.
`card_swiper: ^2.0.4`
