### ISSUE TITLE
Not supported for Flutter 3.0

### ISSUE THREAD

**Issue by md-siam** [TheAnkurPanchani/card_swiper#48]
![Screen Shot 2022-05-27 at 7 12 05 PM](https://user-images.githubusercontent.com/21225918/170707709-4fbe26b9-78b4-4c3e-b0ab-162344ca7311.png)

**Comment by md-siam** [comment]
Please upgrade the package.

**Comment by tasaddaq-hussain** [comment]
Please upgrade the package.

**Comment by tasaddaq-hussain** [comment]
i have same issue please upgrade this pkg.......

**Comment by TheAnkurPanchani** [comment]
Latest release should have fix this. Please check.
`card_swiper: ^2.0.4`

**Comment by md-siam** [comment]
Thanks [TheAnkurPanchani](https://github.com/TheAnkurPanchani)
