### ISSUE TITLE
not supporting v3 flutter

### ISSUE THREAD

**Issue by mahdiqdi** [TheAnkurPanchani/card_swiper#50]
plz update the package.its really important

**Comment by LostInDarkMath** [comment]
Why do you think that Flutter 3 is not supported? I use this library with Flutter 3.0 and it works fine.

**Comment by mahdiqdi** [comment]
> Why do you think that Flutter 3 is not supported? I use this library with Flutter 3.0 and it works fine.
i am using this package with dart fix command but it has some errors and if i did not use that command i couldnt run my project.(now i can run with too many warnings about this package)

**Comment by LostInDarkMath** [comment]
Those are only warnings that you can safely ignore. You can use this package just as before.
And there is a fix on the way in https://github.com/TheAnkurPanchani/card_swiper/issues/50

**Comment by mahdiqdi** [comment]
i knew i can use this package and i did what others say in previous issues but its better to be solved and project runs without any warning.
i wish someone would solve this problem

**Comment by LostInDarkMath** [comment]
As I said, it is already solved here: https://github.com/TheAnkurPanchani/card_swiper/issues/50
It just needs to be merged.

**Comment by TheAnkurPanchani** [comment]
Latest release should have fix this. Please check.
`card_swiper: ^2.0.4`
